FinancistoCloneWeb/Controllers/PokeController.cs
using FinancistoCloneWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace FinancistoCloneWeb.Controllers
{
    [Authorize]
    public class PokeController : BaseController
    {
        private PokemonContext _context;
        public IHostEnvironment _hostEnv;

        public PokeController(PokemonContext context, IHostEnvironment hostEnv):base(context)
        {
            _context = context;
            _hostEnv = hostEnv;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var account = new PokemonGo();            
            var accounts = _context.PokemonGos
                .Where(o => o.UserId == LoggedUser().Id)
                .Include(o => o.Tipo)
                .ToList();
          
            return View(accounts);            
        }


        [HttpGet]
        public ActionResult Create() // GET
        {
            ViewBag.Tipos = _context.TiposL.ToList();
            return View("Create", new PokemonGo());
        }

        [HttpPost]
        public ActionResult Create(PokemonGo pokemonGo, IFormFile image) // POST
        {
            
                
            pokemonGo.UserId = LoggedUser().Id;
          
            if (ModelState.IsValid)
            {
                 pokemonGo.Imagen = SaveImage(image);


                    _context.PokemonGos.Add(pokemonGo);
                    _context.SaveChanges();

                    return RedirectToAction("Index");
                
            }
            ViewBag.Tipos = _context.TiposL.ToList();
            return View("Create", pokemonGo);
        }
        [HttpGet]
        public ActionResult Capturar(int pokemon)
        {
            var captura = new UsuarioPokemonGo
            {
                IdPokemonGo = pokemon,
                IdUser = LoggedUser().Id
            };
            _context.UsuarioPokemonGos.Add(captura);
            _context.SaveChanges();
            RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var account = _context.PokemonGos.Where(o => o.Id == id).FirstOrDefault();
            _context.PokemonGos.Remove(account);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        private string SaveImage(IFormFile image)
        {
            if (image != null && image.Length > 0)
            {
                var basePath = _hostEnv.ContentRootPath + @"\wwwroot";
                var ruta = @"\files\" + image.FileName;

                using (var strem = new FileStream(basePath + ruta, FileMode.Create))
                {
                    image.CopyTo(strem);
                    return ruta;
                }
            }
            return null;
        }

    }
}

FinancistoCloneWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pokemon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pokemon</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Poke" asp-action="Index">Cuentas</a>
                        </li>
                    </ul>
                </div>
                <ul class="navbar-nav ml-md-auto">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a href="/auth/login" class="nav-link text-dark">Login</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a href="/auth/logout" class="nav-link text-dark">Logout</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FinancistoCloneWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>